name: RL_proj_final
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy>=1.19.0
  - torch >=2.7.0
  - scipy>=1.7.0
  - matplotlib>=3.4.0
  - pandas>=1.3.0
  - seaborn>=0.11.0
  - pytorch>=1.12.0
  - tqdm>=4.60.0
  - pip=20.2
  - setuptools=50.3.0
  - wheel=0.35.1
  - pip:
    - pyglet==1.5.0
    - cloudpickle==1.6.0
    - gym==0.21.0